# ifndef _FSL_INCLUDE_H_
# define _FSL_INCLUDE_H_
    #include "stdio.h"    
    //#include "cmath"
    //# include "iostream"
//SDKµ×²ãÇý¶¯¿â
    #include "fsl_adc.h"
    #include "fsl_cache.h"
    #include "fsl_common.h"
    #include "fsl_clock.h"
    #include "fsl_debug_console.h"
    #include "fsl_elcdif.h"
    #include "fsl_enc.h"    
    #include "fsl_gpio.h"
    #include "fsl_gpt.h"
    #include "fsl_iomuxc.h"
    #include "fsl_lpuart.h"
    #include "fsl_lpi2c.h"
    #include "fsl_pwm.h"
    #include "fsl_pit.h"
    #include "fsl_qtmr.h"
    #include "fsl_trng.h"
    #include "fsl_usdhc.h"
    #include "fsl_wdog.h"
    #include "fsl_xbara.h"
    #include "board.h"
    #include "pin_mux.h"
    #include "fsl_flexspi.h"
    #include "fsl_lpuart_edma.h"
    #include "fsl_edma.h"
    #include "fsl_dmamux.h"
    #include "fsl_lpspi.h"
    #include "fsl_sccb.h"

# endif